name: Blocklists Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

env:
  SuperSecret: ${{ secrets.SuperSecret }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python auto_blocklists.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: keanugithub
          author_email: kbricenio@gbox.adnu.edu.ph
          message: 'Automatically committed changes'
