name: Update Blocklists

on:
  schedule:
    - cron: '40 23 * * *'

jobs:
  update_blocklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.1
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Update blocklists
        run: python update_blocklists.py
      - name: Commit changes
        run: |
          git config --global user.email "kabbricenio@gmail.com"
          git config --global user.name "keanugithub"
          git add blocklists.txt
          git commit -m "Update blocklists"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
