name: Update Blocklists v2

on: 
  workflow_dispatch:

jobs:
  update_blocklists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '16.x'
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Update blocklists
        run: python3 auto.py
      - name: Commit changes
        run: |
          git config --global user.email "kabbricenio@gmail.com"
          git config --global user.name "keanugithub"
          git add blocklists.txt
          git commit -m "auto update by script"
      - name: Push changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const message = 'auto update by script';
            const branch = github.context.payload.ref.replace('refs/heads/', '');
            const { data } = await github.repos.createOrUpdateFileContents({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              path: 'blocklists.txt',
              message,
              content: Buffer.from('new content').toString('base64'),
              sha: github.context.sha,
              branch
            });
            console.log(data);
